GET http://localhost:5146/


###
GET http://localhost:5146/products


###
GET http://localhost:5146/products/2

###
POST http://localhost:5146/products
Content-Type: application/json

{
    "name": "Cutting board",
    "price": 5.99,
    "categoryId": 2
}

###
POST http://localhost:5146/products
Content-Type: application/json

{
    "name": "Banana",
    "price": 1.99,
    "categoryId": 1
}